# ASCII-Font › http://patorjk.com/software/taag/#p=display&f=Slant&t=Phlow
#
#      _____ _ __          _____      __  __  _
#     / ___/(_) /____     / ___/___  / /_/ /_(_)___  ____ ______
#     \__ \/ / __/ _ \    \__ \/ _ \/ __/ __/ / __ \/ __ `/ ___/
#    ___/ / / /_/  __/   ___/ /  __/ /_/ /_/ / / / / /_/ (__  )
#   /____/_/\__/\___/   /____/\___/\__/\__/_/_/ /_/\__, /____/
#                                                 /____/
#
# Title of your website
title: "Maker BBQ"


# The slogan describes your website and is used on homepage in <title> and other important places
slogan: "Roll up your sleeves and make cook some meat"


# The description is used on homepage and in the footer to quickly describe your website. Use a maximum of 150 characters for SEO-purposes.
description: "Maker BBQ is a site dedicated to learning about grilling, smoking, and creating and modifying tools to that purpose."


# This URL is the main adresse. Don't include a slash at the end.
#
url: "http://makerbbq.com"
baseurl: ""

# This is for the editing function in _/includes/improve_content.html
# Leave it empty if your site is not on GitHub/GitHub Pages
improve_content: https://github.com/makerbbq/makerbbq.github.io/edit/gh-pages

# This URL points directly to the images directory making
# things easier to link to images in posts and templates. It needs a slash.
#
# Example: <img src="{{ site.urlimg }}/{{ post.image.title }}">
# Markdown-Example for posts ![Image Text]({{ site.urlimg }}/image.jpg)
#
urlimg: "http://makerbbq.com/images/"


# Logo size is 600x80 pixels
logo: "logo.png"


# Paginates all X entries
paginate: 5


# Pagination path › Important for blog page in /blog/ to work
paginate_path: "blog/page:num"


# Theme works best with Kramdown (using the table of contents function)
markdown: kramdown
permalink: /:categories/:title/
highlight: pygments
excerpt_separator: "\n\n"
exclude: []
include: ['.htaccess']


# The language setting is used in /includes/header.html for html-settings
language: "en"

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md


#
#       ____       ____            ____
#      / __ \___  / __/___ ___  __/ / /_
#     / / / / _ \/ /_/ __ `/ / / / / __/
#    / /_/ /  __/ __/ /_/ / /_/ / / /_
#   /_____/\___/_/  \__,_/\__,_/_/\__/
#
# Default Settings

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      show_meta: true # Show metadata beneath all pages
      sidebar: right # Possible values › left, right › by default there will be no sidebar
      comments: false
      author: tim
      header:
         image_fullwidth: "coals-banner.png"

  -
    scope:
      path: ""
      type: "posts"
    values:
      show_meta: true   # Show metadata beneath all posts
      sidebar: right       # Possible values › left, right › by default there will be no sidebar
      comments: true
      author: tim
      header:
         image_fullwidth: "coals-banner.png"



#       _   __            _             __  _
#      / | / /___ __   __(_)___ _____ _/ /_(_)___  ____
#     /  |/ / __ `/ | / / / __ `/ __ `/ __/ / __ \/ __ \
#    / /|  / /_/ /| |/ / / /_/ / /_/ / /_/ / /_/ / / / /
#   /_/ |_/\__,_/ |___/_/\__, /\__,_/\__/_/\____/_/ /_/
#                       /____/
#
#  Open _data/navigation.yml to adjust the left and right topbar navigation
#



#     _____ __________
#    / ___// ____/ __ \
#    \__ \/ __/ / / / /
#   ___/ / /___/ /_/ /
#  /____/_____/\____/    Verify Website to Webmaster Tools

google_author:             "https://google.com/+TimRayburnNET"
# google_site_verification:  "Vk0IOJ2jwG_qEoG7fuEXYqv0m2rLa8P778Fi_GrsgEQ"
pinterest_site_verification: "513ba08faff86d5d7bda56d50e3c8cb0"
bing_webmastertools_id:    "0F699303BA70CC5AC2CF33C4F7B62081"
# alexa_verify_id:         ""



#       ______            _
#      / ____/___ __   __(_)________  ____  _____
#     / /_  / __ `/ | / / / ___/ __ \/ __ \/ ___/
#    / __/ / /_/ /| |/ / / /__/ /_/ / / / (__  )
#   /_/    \__,_/ |___/_/\___/\____/_/ /_/____/   Favicons, Apple Touch Buttons
#                                                 More information » http://j.mp/apple-touch-icons

favicon:                         "/assets/img/logo-32.png"                    # iOS7 Size 32x32
apple_touch_icon_iphone:         "/assets/img/logo-60.png"          # iOS7 Size 60x60
apple_touch_icon_iphone_retina:  "/assets/img/logo-120.png"  # iOS7 Size 120x120
apple_touch_icon_ipad:           "/assets/img/logo-76.png"            # iOS7 Size 76x76
apple_touch_icon_ipad_retina:    "/assets/img/logo-152.png"    # iOS7 Size 152x152
apple_touch_icon_precomposed:    "/assets/img/logo-152.png"        # iOS7 Size 152x152
msapplication_tileimage:         "/assets/img/logo-144.png"       # Windows 8 Tile 144x144
msapplication_tilecolor:         "#334D5C"                                        # Windows 8 Tile Backgroundcolor


#       ______                __                __
#      / ____/___ _________  / /_  ____  ____  / /__
#     / /_  / __ `/ ___/ _ \/ __ \/ __ \/ __ \/ //_/
#    / __/ / /_/ / /__/  __/ /_/ / /_/ / /_/ / ,<
#   /_/    \__,_/\___/\___/_.___/\____/\____/_/|_|      Facebook-Optimization › http://j.mp/fb_optimize

og_image:                           "http://makerbbq.com/assets/img/logo-144.png"
og_locale:                          "en_EN"
og_type:                            "website"
og_title:                           "Maker BBQ"
og_description:                     "Maker BBQ is a site dedicated to learning about grilling, smoking, and creating and modifying tools to that purpose."
og_url:                             "http://makerbbq.com/"
og_site_name:                       "Maker BBQ"


#      _____            _       __   __  ___         ___
#     / ___/____  _____(_)___ _/ /  /  |/  /__  ____/ (_)___ _
#     \__ \/ __ \/ ___/ / __ `/ /  / /|_/ / _ \/ __  / / __ `/
#    ___/ / /_/ / /__/ / /_/ / /  / /  / /  __/ /_/ / / /_/ /
#   /____/\____/\___/_/\__,_/_/  /_/  /_/\___/\__,_/_/\__,_/
#
#  Open _data/socialmedia.yml to adjust the left and right topbar navigation
#


#        ____  _
#       / __ \(_)________ ___  _______
#      / / / / / ___/ __ `/ / / / ___/
#     / /_/ / (__  ) /_/ / /_/ (__  )
#    /_____/_/____/\__, /\__,_/____/
#                    /_/
#
# used in _includes/comments.html

disqus_shortname: makerbbq


#      _____
#     / ___/____ ___________
#     \__ \/ __ `/ ___/ ___/
#    ___/ / /_/ (__  |__  )     More › http://sass-lang.com/
#   /____/\__,_/____/____/      More › http://jekyllrb.com/docs/assets/#sassscss
#

sass:
    sass_dir: _sass
    style: :compressed


#       ___                __      __  _
#      /   |  ____  ____ _/ /_  __/ /_(_)_________
#     / /| | / __ \/ __ `/ / / / / __/ / ___/ ___/
#    / ___ |/ / / / /_/ / / /_/ / /_/ / /__(__  )
#   /_/  |_/_/ /_/\__,_/_/\__, /\__/_/\___/____/      https://www.google.com/analytics/
#                        /____/
#
# used in _includes/footer_scripts.html

google_analytics_tracking_id: UA-2693862-6
